<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class OperatorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Moderator 1 uchun operatorlar ma'lumotlari
        DB::table('operators')->insert([
            [
                'oper_fish' => 'Xujanova Lobar Raimkulovna',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Bo‘lajak tarix o‘qituvchilarining didaktik kompetentligini rivojlantirish metodikasi (tarix)",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 1,
            ],
            [
                'oper_fish' => 'Maxmudova Charos Ikramovna',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Talabalarda geografik ob’ekt va joy nomlarini to‘g‘ri qo‘llay olish kompetensiyasini rivojlantirish metodikasi",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 1,
            ],
            [
                'oper_fish' => 'Ilmurodova Feruza Shokirovna',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Klaster tizimida bo‘lajak tarix o‘qituvchilarini kasbiy faoliyatga tayyorlash metodikasi",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 1,
            ],
            [
                'oper_fish' => 'Sa’dullaeva Mahfuza Husenovna',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Tarix fanlarini o‘qitishda mnemonik texnologiyalar asosida xotirani rivojlantirish metodikasi (oliy ta’lim misolida)",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 1,
            ],
            [
                'oper_fish' => 'Ibragimov Xurshid',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Pedagogika oliygohlarida nazariya va plener amaliyot integratsiyasi asosida intellektual kompetensiyalarni rivojlantirish metodikasi (Rangtasvir fani misolida)",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 1,
            ],
            [
                'oper_fish' => 'Koshanova Shaxlo Maxsudovna',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "3D simulyasiyalari asosida tarix ta’limini rivojlantirish metodikasi",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 1,
            ],
            [
                'oper_fish' => 'Ibragimova Matluba Maxsudovna',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Yangi O‘zbekiston sharoitida badiiy gimnastika sportini tizimli rivojlantirishning pedagogik mehanizmlari",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 1,
            ],
            [
                'oper_fish' => 'To‘raev Azamat Maxsudovich',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "O‘quvchilarning muvaffaqiyatli ijtimoiylashuvini ta’minlashda bo‘sh vaqtni samarali tashkil qilishning pedagogik mexanizmlari",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 1,
            ],
            [
                'oper_fish' => 'Yursinboev Jahongirmirzo Mexrojiddin o‘g‘li',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Tarix ta’limida birlamchi manbalarni integratsiyalashning pedagogik strategiyalari (“Sulton Abdulhamid xotiralari” misolida)",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 1,
            ],
            [
                'oper_fish' => 'Sahobiddinova Mavluda Baxtiyor qizi',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Turkistonda ta’lim tizimidagi islohotlar",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 1,
            ],

        ]);

        // Moderator 2 uchun operatorlar ma'lumotlari
        DB::table('operators')->insert([
            [
                'oper_fish' => 'Jumanova Gulmira Paxriddin qizi',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Ta’lim muassalarini boshqarishning zamonaviy texnologiyalari",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 2,
            ],
            [
                'oper_fish' => 'Mengdobilova Mavluda Qarshiyevna',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Ta’lim sifatini oshirishda darslikga qo‘yiladigan didaktik talablar (tarbiya fani misolida) (PhD)",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 2,
            ],
            [
                'oper_fish' => 'Imomqulova Pokiza MG‘T 20/1',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Zamonaviy jamiyatda ekologik madaniyatni rivojlantirish mexanizmalari",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 2,
            ],
            [
                'oper_fish' => 'Sotvoldiyev Adhamjon -MG‘T 20/1',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Zardushtiylik va islom dinida farzand tarbiyasining qiyosiy tahlili",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 2,
            ],
            [
                'oper_fish' => 'Erjigitov Jonibek MG‘T 20/3',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Zamonaviy jamiyatda intellektual madaniyatni rivojlantirish mexanizmlari",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 2,
            ],
            [
                'oper_fish' => 'Botirova Iroda MG‘T 23/2',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "“Madaniyat talvasasi” hodisasi va unga qarshi kurashning zamonaviy usullari",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 2,
            ],
            [
                'oper_fish' => 'Husanov Jamoliddin - MG‘T 23/1',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Ijtimoiy taraqqiyot va barkamol avlod tarbiyasining o‘zaro dialektik aloqadorligi",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 2,
            ],
            [
                'oper_fish' => 'Halilova Nigina MG‘T 23/2',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Yoshlarni milliy qadriyatlarga sodiqlik ruhida tarbiyalashning metodologik asoslari",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 2,
            ],
            [
                'oper_fish' => 'Sayriddinova Kibriyo MG‘T 23/2',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Zamonaviy jamiyatda axborot madaniyati: ijtimoiy-falsafiy tahlil",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 2,
            ],
            [
                'oper_fish' => 'G‘oyibnazarova Mashhura MG‘T 23/1',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "O‘zbekistonning jahon mafkuraviy jarayonlariga moslashish imkoniyatlari va muammolari",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 2,
            ],

        ]);

        // Moderator 3 uchun operatorlar ma'lumotlari
        DB::table('operators')->insert([
            [
                'oper_fish' => 'Tursunaliyeva Rufina',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Ingliz tilini o‘qitishda harakat fe’llarini o‘rgatish metodikasi",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 3,
            ],
            [
                'oper_fish' => 'Ilyasova Husnorabonu',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Formation of a “secondary” linguistic personality in the process of teaching a foreign language culture",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 3,
            ],
            [
                'oper_fish' => 'Abduraxmonova Zulayho',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Formation of a “secondary” linguistic personality in the process of teaching a foreign language culture",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 3,
            ],
            [
                'oper_fish' => 'Odiljonova Robiya',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Cultural Signifiers in Literature: A Lexical Analysis of Contemporary Novels",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 3,
            ],
            [
                'oper_fish' => 'Xolisova Moxichexra',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Pragmatics: the study of how language is used in social contexts, including the role of context and cultural factors in communication",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 3,
            ],
            [
                'oper_fish' => 'Mahmmudova Dilrabo',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Discussion as a method of developing communication skills in high school",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 3,
            ],
            [
                'oper_fish' => 'Sharipova Shahrizoda',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Communicative language teaching in connection with Total Physical response for young learners",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 3,
            ],
            [
                'oper_fish' => 'Maminova Mashhura',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "The Influence of Literature on Lexical Creativity: A Study of Coined Words in Fiction",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 3,
            ],
            [
                'oper_fish' => 'Akbarova Saida',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Providing the flipped classroom methodology in teaching English in general secondary schools",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 3,
            ],
            [
                'oper_fish' => 'Aliqulova Gulshoda',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Development of critical thinking when teaching reading in English lessons",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 3,
            ],
            [
                'oper_fish' => 'Xolmamatova Ruxshona',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "The method of increasing vocabulary in English through the innovative cluster approach in pedagogical education",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 3,
            ],


        ]);

         // Moderator 4 uchun operatorlar ma'lumotlari
         DB::table('operators')->insert([
            [
                'oper_fish' => 'Xabibullayev Samandar Xabibullayevich',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Jismoniy tarbiya darslarida sport o‘yinlari qoidalarini o‘rgatishning pedagogik mexanizmlarini takomillashtirish",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 4,
            ],
            [
                'oper_fish' => 'Zufarov Timur Umarovich',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Совершенствование педагогических основ обучениya школьников подвижным играм",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 4,
            ],
            [
                'oper_fish' => 'Abduraximov Sardor Dilmurod o`gli',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Gimnastika sport turi orqali maktab o`quvchilari jismoniy sifatlarini valeologik tarbiyalash didaktikasi.",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 4,
            ],
            [
                'oper_fish' => 'Djurabaeva Dilafruz Ergashbaevna (O`qituvchi)',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Sportchilarga Jismoniy mashqlar orqali fiziologiyasining rivojlanishiga Akmeologik ta`sir ko`rsatish nazariyasi",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 4,
            ],
            [
                'oper_fish' => 'Zulxaydarov Javlon Abdukahhor o`g`li (Doktorant)',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Pedagogik taʼlim innovatsion klaster yondashuvida boʻlajak mutaxassislarning kasbiy kompetentligini rivojlantirish. (Jismoniy madaniyat taʼlim yoʻnalishi misolida)",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 4,
            ],
            [
                'oper_fish' => 'Safarova Maxbuba Erkinovna (Magistr)',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "O`quvchi qizlarini jismoniy tarbiyaga yo`naltirish tendensiyiyalari.",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 4,
            ],
            [
                'oper_fish' => 'Boltayeva Sumbula Muzaffar qizi (Talaba)',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Kurashchilarni vatan ruhida tarbiyalashning yuksak kasbiy-pedagogik geografiyasini ommalashtirish dinamikasi",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 4,
            ],
            [
                'oper_fish' => 'Sayfulloyeva Shohigul Shavqiddinovna (Talaba)',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Yengil atletika sport turini o`qitishni zamonaviy loyihalash mexanizmini takomillashtirish",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 4,
            ],
            [
                'oper_fish' => 'Azimova Lutfiya Norsafar qizi (Talaba)',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Basketbol darslarida akmeologik yondashuv orqali o`quvchilar jismoniy qobiliyatlarini shakllantirish didaktikasi",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 4,
            ],
            [
                'oper_fish' => 'Murodova Ruxshona Muzaffar qizi (Talaba)',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Maktab o`quvchilarini sport musobaqalariga tayorlash tizimini takomillashtirish (Voleybol sport turi misolida.)",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 4,
            ],

        ]);


           // Moderator 5 uchun operatorlar ma'lumotlari
           DB::table('operators')->insert([
            [
                'oper_fish' => 'Umarova Ayman Iles qizi',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Maktabgacha ta'lim muassasalari musiqa rahbarining korreksion ritmika metodlarini takomillashtirish.",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 5,
            ],
            [
                'oper_fish' => 'Kimsanov Oxunjon Ilhomjon o‘g‘li',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Oliy ta'lim muassasalarida xalq cholg`u orkestri  ijrochiligining pedagogik an'analari",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 5,
            ],
            [
                'oper_fish' => 'Agzamov Davron.',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Musiqiy ijrochilik tanlovlar talabalarda ansambl malakalarini shakllantirish vositasi sifatida.",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 5,
            ],
            [
                'oper_fish' => 'Muminova Dilshoda.',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Maktabgacha ta'lim muassalarida musiqa tarbiyasi.",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 5,
            ],
            [
                'oper_fish' => 'Mannapova Flora.',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Maktabgacha ta'lim muassalarida musiqiy korreksion ishlar nazariyasi va metodikasi.",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 5,
            ],
            [
                'oper_fish' => 'Klitbekova Go‘zal.',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Musiqiy ijrochilikda konsertmeysterlik mahorati ahamiyati.",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 5,
            ],
            [
                'oper_fish' => 'Begmatova Zarnigor.',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Ansamblli musiqada  fortepiano  ifoda vositalarini o`ziga xos xususiyatlari.",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 5,
            ],
            [
                'oper_fish' => 'Ğafurova Zuhra',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Òzbek musiqa madaniyati rivojida kompozitorlik ijodiyoti.",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 5,
            ],
            [
                'oper_fish' => 'Ne`mataliyev Elyorjon.',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Musiqa madanyati fanini o'rgatishda zamonaviy axborot kommunikatsion texnalogiyalardan foydalanish yo'lari",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 5,
            ],
            [
                'oper_fish' => 'Saidaxmatova Malika',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => "Musiqa madaniyati darslari samaradorligini oshirishda interfaol usullardan foydalanish",
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 5,
            ],

        ]);

        // Moderator 6 uchun operatorlar ma'lumotlari
        DB::table('operators')->insert([
            [
                'oper_fish' => 'Собиров Сарвар Турсунмуротович',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => 'Олий таълимда индивидуал таълимни ташкил этиш муаммолари (Тасвирий санъат мисолида)',
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 6,
            ],
            [
                'oper_fish' => 'Марасулова Иззат МухаматСултановна',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => 'Развитие способностей к креативной деятельности на занятиях декоративно-прикладным искусством.',
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 6,
            ],
            [
                'oper_fish' => 'Отаханова Нодира Жуманазаровна',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => 'Бўлажак тасвирий санъат ўқитувчисининг касбий фазилатларини ривожлантиришда мураббийлик ва педагогик маслаҳатларнинг ўрни',
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 6,
            ],
            [
                'oper_fish' => 'Бердиев Достон Абдувайитович',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => 'Бўлажак педагогларда креатив қобилиятларни СТЕАМ ёндашуви асосида шакллантириш методикаси. (Тасвирий санъат йўналиши мисолида)',
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 6,
            ],
            [
                'oper_fish' => 'Мирсоатова Лайло Ўткир қизи',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => 'Олий таълимда тасвирий санъат ва компютер графикаси интегратсиялаш орқали индивидуал таълимни ташкил этиш.',
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 6,
            ],
            [
                'oper_fish' => 'Имоматова Умида Мирпулатовна',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => 'Педагогик олий таълим муассасаларида талабаларнинг ижодий қобилиятларини ривожлантиришда фанлар интеграциясининг таъсири (Рангтасвир мисолида)',
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 6,
            ],
            [
                'oper_fish' => 'Ўткирова Мамура',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => 'Кластер ёндашуви орқали ўқувчиларнинг бадиий ижодий қобилиятларини ривожлантириш.',
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 6,
            ],
            [
                'oper_fish' => 'Наримонова Шодия Садулла қизи',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => 'Педагогик таълим кластери асосида талабаларга тасвирий санъат машғулотларини ташкил этиш методикаси (қаламтасвир, рангтасвир, композиция фанларининг интеграцияси асосида)',
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 6,
            ],
            [
                'oper_fish' => 'Байназарова Н.Х.',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => 'Тасвирий санъат, дизайн ва технология фанлари интеграцияси',
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 6,
            ],
            [
                'oper_fish' => 'Алимова Нодира Шакатовна',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => 'Тасвирий санъатнинг имконияти чекланган ўқувчилар руҳиятига таъсири (Арт-терапия)',
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 6,
            ],
            [
                'oper_fish' => 'Ғуломова Дилнура',
                'oper_image' => '',
                'oper_status' => 1,
                'oper_custom_ball' => 0,
                'oper_small_info' => 'Фанлар интеграцияси орқали талабаларнинг ижодий тафаккурини ривожлантириш (Миниатюра санъати мисолида)',
                'oper_slug_number' => Str::random(10),
                'moderator_id' => 6,
            ],
           
        ]);

    }
}
